### PR TITLE
go: upgrade deps

### LINKED ISSUE #35: Update to latest golang Protobuf lib
The go-mod should be changed to use:
google.golang.org/protobuf v1.22.0

The github is here:
https://github.com/protocolbuffers/protobuf-go

The new version provides better reflections asepcts

### PR DESCRIPTION
**Pull request by lrstanley**
closes #35

### CODE REVIEW

**Comment by lrstanley** [comment]
Also, I believe with later Go versions, `vendor/` is no longer needed, given https://proxy.golang.org/ exists, and is now a standard and is the default location where packages are fetched from, it should mostly eliminate the need for any kind of vendor directory.

If you're fine with me removing this directory, I can remove it as well.

**Comment by favadi** [comment]
> If you're fine with me removing this directory, I can remove it as well.

This would be great!

**Comment by lrstanley** [comment]
Removed the `vendor/` dir, as well as bumped Go from 1.13 to 1.16 in go.mod & your travis config. Tested successfully locally.

**Comment by favadi** [comment]
Merged, thank @lrstanley

**Pull request merged**
